### ISSUE TITLE
为什么没有兼容到iOS8呢？

### ISSUE THREAD

**Issue by hongdong** [knightsj/SJNetwork#1]
不知道是用了哪些高版本的东西，为什么没有兼容到iOS8，现在8的比重还是有一些的。

**Comment by hongdong** [comment]
还有缓存策略支持先读出缓存，然后请求，请求回来以后刷新缓存。然后再读出来么

**Comment by knightsj** [comment]
已经修改为支持iOS8，谢谢

**Comment by knightsj** [comment]
暂时无法支持。目前的做法是：只要能获取在设定的缓存留存时间之内的缓存就立即返回，不进行网络请求。您提到的这个需求我会考虑设计一套方案，非常感谢

**Comment by hongdong** [comment]
感谢回答
